// File: AGISNodeTypeCodeTemplate.cs
// Folder: Assets/Scripts/AX State Machine/Authoring/
// Purpose: Generates a complete, compilable C# IAGISNodeType class from panel/AI inputs.
//          The caller supplies display name, type ID, schema params, and code bodies.
//          The template wraps them in the correct IAGISNodeType / IAGISNodeRuntime scaffolding.

using System;
using System.Collections.Generic;
using System.Text;
using AGIS.ESM.UGC.Params;

namespace AGIS.ESM.Authoring
{
    /// <summary>
    /// Design-time definition for a single schema param (used by the code template).
    /// </summary>
    [Serializable]
    public sealed class AGISSchemaParamDef
    {
        public string         Key;
        public AGISParamType  Type;
        public string         DefaultValueLiteral; // e.g. "1.0f", "\"hello\"", "true"
        public string         DisplayName;
        public string         Tooltip;
    }

    public static class AGISNodeTypeCodeTemplate
    {
        /// <summary>
        /// Generates a fully compilable C# source file for a node type.
        /// </summary>
        /// <param name="displayName">Human-readable name shown in the editor.</param>
        /// <param name="typeId">Unique string ID (e.g. "my.custom_state").</param>
        /// <param name="schemaParams">Schema params the node exposes in the inspector.</param>
        /// <param name="privateFields">Declarations placed inside the Runtime class (e.g. <c>private float _timer;</c>).</param>
        /// <param name="ctorBody">Lines placed inside Runtime's constructor (after <c>_ctx = ctx;</c>).</param>
        /// <param name="enterBody">Body of Enter().</param>
        /// <param name="tickBody">Body of Tick(float dt).</param>
        /// <param name="exitBody">Body of Exit().</param>
        /// <param name="helperMethods">Additional private methods placed inside Runtime.</param>
        public static string Generate(
            string                            displayName,
            string                            typeId,
            IReadOnlyList<AGISSchemaParamDef> schemaParams,
            string                            privateFields   = null,
            string                            ctorBody        = null,
            string                            enterBody       = null,
            string                            tickBody        = null,
            string                            exitBody        = null,
            string                            helperMethods   = null)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// Auto-generated by AGISNodeTypeCodeTemplate — do not edit manually.");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using AGIS.ESM.Runtime;");
            sb.AppendLine("using AGIS.ESM.UGC;");
            sb.AppendLine("using AGIS.ESM.UGC.Params;");
            sb.AppendLine("using AGIS.ESM.Knowledge;");
            sb.AppendLine("using AGIS.ESM.Networking;");
            sb.AppendLine("using AGIS.NPC;");
            sb.AppendLine();
            sb.AppendLine("namespace AGIS.ESM.Authored");
            sb.AppendLine("{");

            string className = ToClassName(typeId) + "NodeType";

            sb.AppendLine($"    public sealed class {className} : IAGISNodeType");
            sb.AppendLine("    {");
            sb.AppendLine($"        public string TypeId      => \"{Esc(typeId)}\";");
            sb.AppendLine($"        public string DisplayName => \"{Esc(displayName)}\";");
            sb.AppendLine("        public AGISNodeKind Kind  => AGISNodeKind.Normal;");
            sb.AppendLine("        public AGISParamSchema Schema { get; } = BuildSchema();");
            sb.AppendLine();

            // BuildSchema()
            sb.AppendLine("        private static AGISParamSchema BuildSchema()");
            sb.AppendLine("        {");
            sb.AppendLine("            var s = new AGISParamSchema();");
            if (schemaParams != null)
            {
                foreach (var p in schemaParams)
                {
                    if (string.IsNullOrEmpty(p?.Key)) continue;
                    string defVal = BuildDefaultValue(p.Type, p.DefaultValueLiteral);
                    sb.AppendLine(
                        $"            s.AddOrReplace(new AGISParamSpec {{ key = \"{Esc(p.Key)}\", " +
                        $"type = AGISParamType.{p.Type}, " +
                        $"defaultValue = {defVal}, " +
                        $"displayName = \"{Esc(p.DisplayName ?? p.Key)}\", " +
                        $"tooltip = \"{Esc(p.Tooltip ?? string.Empty)}\" }});");
                }
            }
            sb.AppendLine("            return s;");
            sb.AppendLine("        }");
            sb.AppendLine();

            // CreateRuntime factory
            sb.AppendLine("        public IAGISNodeRuntime CreateRuntime(in AGISNodeRuntimeCreateArgs args)");
            sb.AppendLine("            => new Runtime(args.Ctx, args.Params);");
            sb.AppendLine();

            // ── Runtime inner class ────────────────────────────────────────────
            sb.AppendLine("        private sealed class Runtime : IAGISNodeRuntime");
            sb.AppendLine("        {");
            sb.AppendLine("            private readonly AGISExecutionContext _ctx;");

            AppendIndented(sb, privateFields, 3);

            sb.AppendLine();
            sb.AppendLine("            public Runtime(AGISExecutionContext ctx, IAGISParamAccessor p)");
            sb.AppendLine("            {");
            sb.AppendLine("                _ctx = ctx;");
            AppendIndented(sb, ctorBody, 4);
            sb.AppendLine("            }");
            sb.AppendLine();

            sb.AppendLine("            public void Enter()");
            sb.AppendLine("            {");
            AppendIndented(sb, enterBody, 4);
            sb.AppendLine("            }");
            sb.AppendLine();

            sb.AppendLine("            public void Tick(float dt)");
            sb.AppendLine("            {");
            AppendIndented(sb, tickBody, 4);
            sb.AppendLine("            }");
            sb.AppendLine();

            sb.AppendLine("            public void Exit()");
            sb.AppendLine("            {");
            AppendIndented(sb, exitBody, 4);
            sb.AppendLine("            }");

            if (!string.IsNullOrWhiteSpace(helperMethods))
            {
                sb.AppendLine();
                AppendIndented(sb, helperMethods, 3);
            }

            sb.AppendLine("        }");  // end Runtime
            sb.AppendLine("    }");      // end class
            sb.AppendLine("}");          // end namespace

            return sb.ToString();
        }

        // ── Helpers ───────────────────────────────────────────────────────────

        /// <summary>Converts a type ID like "npc.follow_target" → "NpcFollowTarget".</summary>
        public static string ToClassName(string typeId)
        {
            if (string.IsNullOrEmpty(typeId)) return "CustomType";
            var parts = typeId.Replace('.', '_').Split('_');
            var sb = new StringBuilder();
            foreach (var part in parts)
                if (part.Length > 0)
                    sb.Append(char.ToUpperInvariant(part[0]) + (part.Length > 1 ? part.Substring(1) : ""));
            return sb.ToString();
        }

        private static string Esc(string s)
            => s?.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "") ?? "";

        private static string BuildDefaultValue(AGISParamType type, string literal)
        {
            if (string.IsNullOrEmpty(literal))
            {
                return type switch
                {
                    AGISParamType.Bool   => "AGISValue.FromBool(false)",
                    AGISParamType.Int    => "AGISValue.FromInt(0)",
                    AGISParamType.Float  => "AGISValue.FromFloat(0f)",
                    AGISParamType.String => "AGISValue.FromString(\"\")",
                    _                   => "default",
                };
            }
            return type switch
            {
                AGISParamType.Bool   => $"AGISValue.FromBool({literal})",
                AGISParamType.Int    => $"AGISValue.FromInt({literal})",
                AGISParamType.Float  => $"AGISValue.FromFloat({literal})",
                AGISParamType.String => $"AGISValue.FromString({literal})",
                _                   => $"AGISValue.FromString(\"{Esc(literal)}\")",
            };
        }

        /// <summary>Appends each non-empty line of <paramref name="code"/> with <paramref name="indentLevel"/>×4 spaces of indentation.</summary>
        private static void AppendIndented(StringBuilder sb, string code, int indentLevel)
        {
            if (string.IsNullOrWhiteSpace(code)) return;
            string indent = new string(' ', indentLevel * 4);
            foreach (var raw in code.Split('\n'))
            {
                string line = raw.TrimEnd('\r');
                sb.AppendLine(indent + line);
            }
        }
    }
}
