// File: AGISConditionTypeCodeTemplate.cs
// Folder: Assets/Scripts/AX State Machine/Authoring/
// Purpose: Generates a complete, compilable C# IAGISConditionType class from panel/AI inputs.

using System.Collections.Generic;
using System.Text;
using AGIS.ESM.UGC.Params;

namespace AGIS.ESM.Authoring
{
    public static class AGISConditionTypeCodeTemplate
    {
        /// <summary>
        /// Generates a fully compilable C# source file for a condition type.
        /// </summary>
        /// <param name="displayName">Human-readable name shown in the editor.</param>
        /// <param name="typeId">Unique string ID (e.g. "my.custom_check").</param>
        /// <param name="schemaParams">Schema params the condition exposes in the inspector.</param>
        /// <param name="evaluateBody">Body of Evaluate() — must return bool.</param>
        /// <param name="helperMethods">Additional private static methods appended to the class.</param>
        public static string Generate(
            string                            displayName,
            string                            typeId,
            IReadOnlyList<AGISSchemaParamDef> schemaParams,
            string                            evaluateBody  = null,
            string                            helperMethods = null)
        {
            var sb = new StringBuilder();

            sb.AppendLine("// Auto-generated by AGISConditionTypeCodeTemplate — do not edit manually.");
            sb.AppendLine("using System;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using AGIS.ESM.Runtime;");
            sb.AppendLine("using AGIS.ESM.UGC;");
            sb.AppendLine("using AGIS.ESM.UGC.Params;");
            sb.AppendLine("using AGIS.ESM.Knowledge;");
            sb.AppendLine("using AGIS.ESM.Networking;");
            sb.AppendLine("using AGIS.NPC;");
            sb.AppendLine();
            sb.AppendLine("namespace AGIS.ESM.Authored");
            sb.AppendLine("{");

            string className = AGISNodeTypeCodeTemplate.ToClassName(typeId) + "ConditionType";

            sb.AppendLine($"    public sealed class {className} : IAGISConditionType");
            sb.AppendLine("    {");
            sb.AppendLine($"        public string TypeId      => \"{Esc(typeId)}\";");
            sb.AppendLine($"        public string DisplayName => \"{Esc(displayName)}\";");
            sb.AppendLine("        public AGISParamSchema Schema { get; } = BuildSchema();");
            sb.AppendLine();

            // BuildSchema()
            sb.AppendLine("        private static AGISParamSchema BuildSchema()");
            sb.AppendLine("        {");
            sb.AppendLine("            var s = new AGISParamSchema();");
            if (schemaParams != null)
            {
                foreach (var p in schemaParams)
                {
                    if (string.IsNullOrEmpty(p?.Key)) continue;
                    string defVal = BuildDefaultValue(p.Type, p.DefaultValueLiteral);
                    sb.AppendLine(
                        $"            s.AddOrReplace(new AGISParamSpec {{ key = \"{Esc(p.Key)}\", " +
                        $"type = AGISParamType.{p.Type}, " +
                        $"defaultValue = {defVal}, " +
                        $"displayName = \"{Esc(p.DisplayName ?? p.Key)}\", " +
                        $"tooltip = \"{Esc(p.Tooltip ?? string.Empty)}\" }});");
                }
            }
            sb.AppendLine("            return s;");
            sb.AppendLine("        }");
            sb.AppendLine();

            // Evaluate
            sb.AppendLine("        public bool Evaluate(in AGISConditionEvalArgs args)");
            sb.AppendLine("        {");
            if (!string.IsNullOrWhiteSpace(evaluateBody))
            {
                foreach (var raw in evaluateBody.Split('\n'))
                    sb.AppendLine("            " + raw.TrimEnd('\r'));
            }
            else
            {
                sb.AppendLine("            return false; // TODO: implement");
            }
            sb.AppendLine("        }");

            if (!string.IsNullOrWhiteSpace(helperMethods))
            {
                sb.AppendLine();
                foreach (var raw in helperMethods.Split('\n'))
                    sb.AppendLine("        " + raw.TrimEnd('\r'));
            }

            sb.AppendLine("    }");  // end class
            sb.AppendLine("}");      // end namespace

            return sb.ToString();
        }

        private static string Esc(string s)
            => s?.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "") ?? "";

        private static string BuildDefaultValue(AGISParamType type, string literal)
        {
            if (string.IsNullOrEmpty(literal))
            {
                return type switch
                {
                    AGISParamType.Bool   => "AGISValue.FromBool(false)",
                    AGISParamType.Int    => "AGISValue.FromInt(0)",
                    AGISParamType.Float  => "AGISValue.FromFloat(0f)",
                    AGISParamType.String => "AGISValue.FromString(\"\")",
                    _                   => "default",
                };
            }
            return type switch
            {
                AGISParamType.Bool   => $"AGISValue.FromBool({literal})",
                AGISParamType.Int    => $"AGISValue.FromInt({literal})",
                AGISParamType.Float  => $"AGISValue.FromFloat({literal})",
                AGISParamType.String => $"AGISValue.FromString({literal})",
                _                   => $"AGISValue.FromString(\"{Esc(literal)}\")",
            };
        }
    }
}
